var _a_p_i_setup_view_model_8cs =
[
    [ "SECUiDEA_ERP_Server.Models.ControllerModels.Private.APISetupViewModel", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1_private_1_1_a_p_i_setup_view_model.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1_private_1_1_a_p_i_setup_view_model" ]
];