var _database_type_json_converter_8cs =
[
    [ "SECUiDEA_ERP_Server.Models.DBServices.DatabaseTypeJsonConverter", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_d_b_services_1_1_database_type_json_converter.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_d_b_services_1_1_database_type_json_converter" ]
];