var _n_lobby_visitor_models_8cs =
[
    [ "SECUiDEA_ERP_Server.Models.ControllerModels.api.NLobby.NLobbyVisitorDTO", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_n_lobby_1_1_n_lobby_visitor_d_t_o.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_n_lobby_1_1_n_lobby_visitor_d_t_o" ],
    [ "SECUiDEA_ERP_Server.Models.ControllerModels.api.NLobby.NLobbyVisitorDeleteDTO", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_n_lobby_1_1_n_lobby_visitor_delete_d_t_o.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_n_lobby_1_1_n_lobby_visitor_delete_d_t_o" ]
];