var _person_model_8cs =
[
    [ "SECUiDEA_ERP_Server.Models.ControllerModels.api.Visit.GetPersonModel", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_visit_1_1_get_person_model.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_visit_1_1_get_person_model" ],
    [ "SECUiDEA_ERP_Server.Models.ControllerModels.api.Visit.EmployeeDTO", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_visit_1_1_employee_d_t_o.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_visit_1_1_employee_d_t_o" ]
];