var _request_models_8cs =
[
    [ "SECUiDEA_ERP_Server.Models.ControllerModels.Aligo.SendRequestModel", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1_aligo_1_1_send_request_model.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1_aligo_1_1_send_request_model" ]
];