var _s1_user_d_t_o_8cs =
[
    [ "SECUiDEA_ERP_Server.Models.ControllerModels.api.Login.S1AuthModel.S1UserDTO", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_login_1_1_s1_auth_model_1_1_s1_user_d_t_o.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_login_1_1_s1_auth_model_1_1_s1_user_d_t_o" ]
];