var _visit_list_model_8cs =
[
    [ "SECUiDEA_ERP_Server.Models.ControllerModels.api.Visit.VisitListItemDTO", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_visit_1_1_visit_list_item_d_t_o.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_visit_1_1_visit_list_item_d_t_o" ],
    [ "SECUiDEA_ERP_Server.Models.ControllerModels.api.Visit.VisitStatusDTO", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_visit_1_1_visit_status_d_t_o.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_visit_1_1_visit_status_d_t_o" ],
    [ "SECUiDEA_ERP_Server.Models.ControllerModels.api.Visit.VisitReserveListParam", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_visit_1_1_visit_reserve_list_param.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_models_1_1_controller_models_1_1api_1_1_visit_1_1_visit_reserve_list_param" ]
];