var i_parking_controller_8cs =
[
    [ "SECUiDEA_ERP_Server.Controllers.api.Parking.IParkingController", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_controllers_1_1api_1_1_parking_1_1_i_parking_controller.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_controllers_1_1api_1_1_parking_1_1_i_parking_controller" ],
    [ "SECUiDEA_ERP_Server.Controllers.api.Parking.IParkingSetupService", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_controllers_1_1api_1_1_parking_1_1_i_parking_setup_service.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_controllers_1_1api_1_1_parking_1_1_i_parking_setup_service" ]
];