var namespace_s_e_c_ui_d_e_a___e_r_p___server_1_1_controllers_1_1api_1_1_aligo =
[
    [ "AligoController", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_controllers_1_1api_1_1_aligo_1_1_aligo_controller.html", "class_s_e_c_ui_d_e_a___e_r_p___server_1_1_controllers_1_1api_1_1_aligo_1_1_aligo_controller" ]
];